const seedData = {
  users: [
    {
      id: 'usr_default_123',
      name: 'Carlos',
      email: 'carlos@teamfit.com',
      password: '$2a$10$e8w8q...',
      age: '32',
      weight: '82',
      size: 'M',
      height: '178',
      goal: 'Tonificar y ganar masa muscular',
      themePreference: 'dark',
    },
  ],
  biometrics: [
    {
      userId: 'usr_default_123',
      date: new Date().toISOString().split('T')[0],
      steps: 8450,
      stepsGoal: 10000,
      stepsPercentage: 84,
      activeCalories: 520,
      caloriesGoal: 700,
      streakDays: 12,
      restingHeartRate: 62,
      biochemScore: 92,
    },
  ],
  nutrition: [
    {
      userId: 'usr_default_123',
      date: new Date().toISOString().split('T')[0],
      caloriesConsumed: 1650,
      caloriesTarget: 2400,
      caloriesRemaining: 750,
      caloriesBurned: 520,
      macros: {
        protein: { current: 145, target: 180, unit: 'g' },
        carbs: { current: 185, target: 220, unit: 'g' },
        fats: { current: 48, target: 65, unit: 'g' },
      },
    },
  ],
  recipes: [
    {
      id: 'rec1',
      title: 'Bowl Proteico de Salmón & Quinoa',
      category: 'Almuerzo / Cena',
      prepTime: '20 min',
      calories: 580,
      protein: 42,
      carbs: 45,
      fat: 18,
      ragBadge: 'Sugerido RAG Bóveda Médica',
      ragReason: 'Optimizado para reducir la PCR Ultrasensible por alto contenido en Omega-3.',
      ingredients: [
        '180g de filete de salmón fresco',
        '1/2 taza de quinoa cocida',
        '1/2 aguacate en rodajas',
        '1 taza de espinacas baby',
        '1 cucharada de semillas de sésamo',
        'Aderezo de aceite de oliva extra virgen y limón',
      ],
      preparationSteps: [
        'Sazonar el salmón con sal marina, pimienta y limón.',
        'Sellar en la sartén a fuego medio durante 4 minutos por lado.',
        'Colocar las espinacas y quinoa en la base del bowl.',
        'Añadir el salmón, el aguacate y espolvorear las semillas de sésamo.',
        'Rociar con aceite de oliva extra virgen.',
      ],
    },
    {
      id: 'rec2',
      title: 'Omelette Antiinflamatorio de Claras y Cúrcuma',
      category: 'Desayuno',
      prepTime: '12 min',
      calories: 340,
      protein: 35,
      carbs: 12,
      fat: 14,
      ragBadge: 'Sugerido RAG Nutricional',
      ragReason: 'La cúrcuma y la espinaca modulan la respuesta del Cortisol matutino.',
      ingredients: [
        '4 claras de huevo + 1 huevo entero',
        '1/2 taza de champiñones laminados',
        '1/2 cucharadita de cúrcuma en polvo',
        'Pizca de pimienta negra (activa la curcumina)',
        '1/4 de taza de queso feta bajo en grasa',
      ],
      preparationSteps: [
        'Batir los huevos con la cúrcuma y pimienta negra.',
        'Saltear los champiñones en una sartén antiadherente.',
        'Verter la mezcla de huevo y cocinar a fuego bajo.',
        'Agregar el queso feta y doblar a la mitad.',
      ],
    },
  ],
  smoothies: [
    {
      id: 'sm1',
      title: 'Verde Metabólico & Depurativo',
      type: 'verde',
      phase: 'FASE ACTIVA: OPTIMIZACIÓN DEL PROGRESO',
      consumptionTiming: 'Toma matutina en ayunas',
      ingredients: [
        '1 taza de espinacas frescas',
        '1/2 manzana verde',
        '1 trozo de jengibre fresco (1cm)',
        '1/2 pepino con piel',
        '1 vaso de agua de coco (250ml)',
        'Jugo de 1/2 limón',
      ],
      benefits: [
        'Depuración hepática matutina',
        'Modulación de glucosa en sangre',
        'Aporte biodisponible de clorofila y magnesio',
      ],
      isConsumed: true,
    },
    {
      id: 'sm2',
      title: 'Batido Funcional Antiinflamatorio Post-Entreno',
      type: 'antiinflamatorio',
      phase: 'FASE ACTIVA: RECUPERACIÓN BIOQUÍMICA',
      consumptionTiming: 'Post-entrenamiento (primeros 30 min)',
      ingredients: [
        '1 scoop de proteína aislada de suero',
        '1/2 cucharadita de cúrcuma pura',
        '1/4 cucharadita de pimienta negra',
        '1/2 taza de frutos rojos congelados',
        '1 cucharada de semillas de chía',
        '300ml de leche de almendras sin azúcar',
      ],
      benefits: [
        'Descenso acelerado de la PCR Ultrasensible',
        'Síntesis proteica muscular avanzada',
        'Control de inflamación articular pos-esfuerzo',
      ],
      isConsumed: true,
    },
  ],
  routines: [
    {
      id: 'rout1',
      title: 'Rutina Full Body',
      phase: 'DÍA 14 / 360 | Fase 1: Condicionamiento Metabólico',
      day: 14,
      durationSeconds: 900,
      durationFormatted: '15:00',
      progressSeconds: 315,
      progressFormatted: '05:15',
      heartRateBpm: 128,
      targetZone: 'Zona 2 Cardio (Optimizada Bóveda Médica)',
      burnedCalories: 185,
      videoUrl: 'https://storage.googleapis.com/teamfit-media/routine-fullbody-demo.mp4',
      exercises: [
        { id: 'ex1', name: 'Sentadilla Goblet', sets: 4, reps: '12 - 15', restSeconds: 60 },
        { id: 'ex2', name: 'Flexiones de Pecho Estrictas', sets: 4, reps: '10 - 12', restSeconds: 60 },
        { id: 'ex3', name: 'Remo con Mancuerna Unilateral', sets: 3, reps: '12 por lado', restSeconds: 45 },
        { id: 'ex4', name: 'Plancha Abdominal Dinámica', sets: 3, reps: '45 segundos', restSeconds: 30 },
      ],
    },
  ],
  biomarkers: [
    {
      userId: 'usr_default_123',
      id: 'bm1',
      name: 'Glucosa en Ayunas',
      value: '88',
      unit: 'mg/dL',
      referenceRange: '70 - 99 mg/dL',
      status: 'optimal',
      statusLabel: 'Óptimo',
      category: 'Metabolismo',
    },
    {
      userId: 'usr_default_123',
      id: 'bm2',
      name: 'Cortisol Matutino',
      value: '18.4',
      unit: 'µg/dL',
      referenceRange: '5.0 - 15.0 µg/dL',
      status: 'high',
      statusLabel: 'Alto (Estrés)',
      category: 'Hormonal',
    },
    {
      userId: 'usr_default_123',
      id: 'bm3',
      name: 'PCR Ultrasensible',
      value: '3.2',
      unit: 'mg/L',
      referenceRange: '< 1.0 mg/L',
      status: 'high',
      statusLabel: 'Alto (Inflamación)',
      category: 'Biomarcador Inflamatorio',
    },
    {
      userId: 'usr_default_123',
      id: 'bm4',
      name: 'Vitamina D3 (25-OH)',
      value: '54',
      unit: 'ng/mL',
      referenceRange: '30 - 80 ng/mL',
      status: 'optimal',
      statusLabel: 'Óptimo',
      category: 'Micronutrientes',
    },
    {
      userId: 'usr_default_123',
      id: 'bm5',
      name: 'Triglicéridos',
      value: '105',
      unit: 'mg/dL',
      referenceRange: '< 150 mg/dL',
      status: 'stable',
      statusLabel: 'Estable',
      category: 'Perfil Lipídico',
    },
    {
      userId: 'usr_default_123',
      id: 'bm6',
      name: 'Colesterol HDL',
      value: '58',
      unit: 'mg/dL',
      referenceRange: '> 40 mg/dL',
      status: 'optimal',
      statusLabel: 'Óptimo',
      category: 'Perfil Lipídico',
    },
  ],
  coach_messages: [
    {
      userId: 'usr_default_123',
      sender: 'coach',
      content: '¡Vamos Carlos! Veo que tu ritmo bajó. Aprieta el paso, faltan solo 3 minutos.',
      timestamp: new Date().toISOString(),
    },
  ],
};

module.exports = seedData;
